<?php
/**
 * RootServerBaseStatisticsMeetings
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BMLT
 *
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RootServerBaseStatisticsMeetings Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RootServerBaseStatisticsMeetings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RootServerBase_statistics_meetings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'num_total' => 'int',
        'num_in_person' => 'int',
        'num_virtual' => 'int',
        'num_hybrid' => 'int',
        'num_unknown' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'num_total' => null,
        'num_in_person' => null,
        'num_virtual' => null,
        'num_hybrid' => null,
        'num_unknown' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'num_total' => false,
		'num_in_person' => false,
		'num_virtual' => false,
		'num_hybrid' => false,
		'num_unknown' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'num_total' => 'numTotal',
        'num_in_person' => 'numInPerson',
        'num_virtual' => 'numVirtual',
        'num_hybrid' => 'numHybrid',
        'num_unknown' => 'numUnknown'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'num_total' => 'setNumTotal',
        'num_in_person' => 'setNumInPerson',
        'num_virtual' => 'setNumVirtual',
        'num_hybrid' => 'setNumHybrid',
        'num_unknown' => 'setNumUnknown'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'num_total' => 'getNumTotal',
        'num_in_person' => 'getNumInPerson',
        'num_virtual' => 'getNumVirtual',
        'num_hybrid' => 'getNumHybrid',
        'num_unknown' => 'getNumUnknown'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('num_total', $data ?? [], null);
        $this->setIfExists('num_in_person', $data ?? [], null);
        $this->setIfExists('num_virtual', $data ?? [], null);
        $this->setIfExists('num_hybrid', $data ?? [], null);
        $this->setIfExists('num_unknown', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['num_total'] === null) {
            $invalidProperties[] = "'num_total' can't be null";
        }
        if ($this->container['num_in_person'] === null) {
            $invalidProperties[] = "'num_in_person' can't be null";
        }
        if ($this->container['num_virtual'] === null) {
            $invalidProperties[] = "'num_virtual' can't be null";
        }
        if ($this->container['num_hybrid'] === null) {
            $invalidProperties[] = "'num_hybrid' can't be null";
        }
        if ($this->container['num_unknown'] === null) {
            $invalidProperties[] = "'num_unknown' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets num_total
     *
     * @return int
     */
    public function getNumTotal()
    {
        return $this->container['num_total'];
    }

    /**
     * Sets num_total
     *
     * @param int $num_total num_total
     *
     * @return self
     */
    public function setNumTotal($num_total)
    {
        if (is_null($num_total)) {
            throw new \InvalidArgumentException('non-nullable num_total cannot be null');
        }
        $this->container['num_total'] = $num_total;

        return $this;
    }

    /**
     * Gets num_in_person
     *
     * @return int
     */
    public function getNumInPerson()
    {
        return $this->container['num_in_person'];
    }

    /**
     * Sets num_in_person
     *
     * @param int $num_in_person num_in_person
     *
     * @return self
     */
    public function setNumInPerson($num_in_person)
    {
        if (is_null($num_in_person)) {
            throw new \InvalidArgumentException('non-nullable num_in_person cannot be null');
        }
        $this->container['num_in_person'] = $num_in_person;

        return $this;
    }

    /**
     * Gets num_virtual
     *
     * @return int
     */
    public function getNumVirtual()
    {
        return $this->container['num_virtual'];
    }

    /**
     * Sets num_virtual
     *
     * @param int $num_virtual num_virtual
     *
     * @return self
     */
    public function setNumVirtual($num_virtual)
    {
        if (is_null($num_virtual)) {
            throw new \InvalidArgumentException('non-nullable num_virtual cannot be null');
        }
        $this->container['num_virtual'] = $num_virtual;

        return $this;
    }

    /**
     * Gets num_hybrid
     *
     * @return int
     */
    public function getNumHybrid()
    {
        return $this->container['num_hybrid'];
    }

    /**
     * Sets num_hybrid
     *
     * @param int $num_hybrid num_hybrid
     *
     * @return self
     */
    public function setNumHybrid($num_hybrid)
    {
        if (is_null($num_hybrid)) {
            throw new \InvalidArgumentException('non-nullable num_hybrid cannot be null');
        }
        $this->container['num_hybrid'] = $num_hybrid;

        return $this;
    }

    /**
     * Gets num_unknown
     *
     * @return int
     */
    public function getNumUnknown()
    {
        return $this->container['num_unknown'];
    }

    /**
     * Sets num_unknown
     *
     * @param int $num_unknown num_unknown
     *
     * @return self
     */
    public function setNumUnknown($num_unknown)
    {
        if (is_null($num_unknown)) {
            throw new \InvalidArgumentException('non-nullable num_unknown cannot be null');
        }
        $this->container['num_unknown'] = $num_unknown;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


